// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQGkMu4toqJUEO7VvmmPdakt3Q2Rp5hFA',
    appId: '1:1040122834483:web:f1c30e65cff72aea75bd46',
    messagingSenderId: '1040122834483',
    projectId: 'bons-plans-f2ec5',
    authDomain: 'bons-plans-f2ec5.firebaseapp.com',
    storageBucket: 'bons-plans-f2ec5.appspot.com',
    measurementId: 'G-MBBHYBJW2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXjk9QlF3KYN0zV_C4k9p5aRl7ORLc9Aw',
    appId: '1:1040122834483:android:340bb88b7e8bc23075bd46',
    messagingSenderId: '1040122834483',
    projectId: 'bons-plans-f2ec5',
    storageBucket: 'bons-plans-f2ec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb00gQ2aFCmnx2ebvgn3QPLSioQGqCyVE',
    appId: '1:1040122834483:ios:58f8115ad132c9c175bd46',
    messagingSenderId: '1040122834483',
    projectId: 'bons-plans-f2ec5',
    storageBucket: 'bons-plans-f2ec5.appspot.com',
    iosBundleId: 'com.ASEDS.BonsPlans.aseds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb00gQ2aFCmnx2ebvgn3QPLSioQGqCyVE',
    appId: '1:1040122834483:ios:58f8115ad132c9c175bd46',
    messagingSenderId: '1040122834483',
    projectId: 'bons-plans-f2ec5',
    storageBucket: 'bons-plans-f2ec5.appspot.com',
    iosBundleId: 'com.ASEDS.BonsPlans.aseds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQGkMu4toqJUEO7VvmmPdakt3Q2Rp5hFA',
    appId: '1:1040122834483:web:644e4cb62752d30b75bd46',
    messagingSenderId: '1040122834483',
    projectId: 'bons-plans-f2ec5',
    authDomain: 'bons-plans-f2ec5.firebaseapp.com',
    storageBucket: 'bons-plans-f2ec5.appspot.com',
    measurementId: 'G-81MY1CM5D7',
  );

}